import assert from 'node:assert/strict';
import {loadModule} from './load-module.mjs';
const {evaluatePlayer,normalizeSettings,rosterOutcomeValue,analyzeDraft}=await loadModule('../lib/optimizer.ts');
const {applyDiscordRules}=await loadModule('../lib/discord-rules.ts');
const input={userTeam:'Super Smash Burrows',draftSlot:8,scoring:'ppr',mode:'balanced',starters:{QB:1,RB:2,WR:2,TE:1,FLEX:2,K:1,DST:1},keeperRules:{limit:3,escalation:1,horizon:3,discount:.65,firstRound:'ineligible',collision:'reject'}};
const s=normalizeSettings(applyDiscordRules(input));
assert.equal(s.draftSlot,8);assert.deepEqual(s.keeperRules,input.keeperRules);assert.equal(s.starters.WR,3);assert.equal(s.starters.FLEX,0);assert.equal(s.customScoring.pass_ints,-2);assert.equal(s.customScoring.def_sack,2);
const player=(pos,stats,points)=>({id:pos,name:pos,pos,team:'HOU',stats,pointsByScoring:{standard:points,ppr:points},projectedPoints:points,projectionScoring:'standard',season:2026,adp:100,age:25,dynastyRank:999,tier:1,bye:7,hasProjection:true});
const k=player('K',{fg:30,xpt:40},130);const d=player('DST',{def_sack:40,def_int:10,def_fr:10,def_safety:1,def_td:3},100);
const ek=evaluatePlayer(k,s),ed=evaluatePlayer(d,s);
assert.ok(ek.estimatedBonusPoints>0);assert.equal(ek.value,130+ek.estimatedBonusPoints);
assert.equal(ed.value,140+ed.estimatedBonusPoints); // two points per sack, PLUS PA band estimate
assert.ok(ek.bonusDetails.some(x=>x.includes('Estimated FG')));assert.ok(ed.issues.some(x=>x.includes('not reconciled')));
const constant=evaluatePlayer(k,{...s,bonusRules:{fieldGoals:[3,3,3]}});assert.equal(constant.estimatedBonusPoints,0);
const negative=evaluatePlayer(d,{...s,bonusRules:{pointsAllowed:[-1,-1,-1,-1,-1,-1,-1]}});assert.ok(Math.abs(negative.estimatedBonusPoints+17)<1e-10);
assert.ok(Math.abs(evaluatePlayer(k,{...s,customScoring:{...s.customScoring,fg:4}}).value-ek.value)<1e-10,'Total band values replace flat FG coefficient exactly once');
assert.equal(evaluatePlayer({...k,season:2025},s).estimatedBonusPoints,0,'No future-trained data in historical season');
assert.match(evaluatePlayer({...k,season:2025},s).issues.join(' '),/season mismatch/);
assert.equal(evaluatePlayer({...k,stats:{}},s).estimatedBonusPoints,0);
assert.equal(evaluatePlayer({...k,pointsByScoring:{standard:150}},s).estimatedBonusPoints,0,'Upstream changed baseline cannot double count');
assert.equal(evaluatePlayer(k,{...s,bonusRules:{fieldGoals:[NaN,4,5]}}).estimatedBonusPoints,0);
const simple=normalizeSettings({...input,starters:{QB:1,RB:0,WR:0,TE:0,FLEX:0,K:0,DST:0},bench:1});
const starter={...evaluatePlayer(player('QB',{},200),simple),id:'starter',bye:0};
const backup={...starter,id:'backup',value:100};
const outcomes=new Map([['starter',{...starter,value:10}],['backup',{...backup,value:1000}]]);
const value=rosterOutcomeValue([starter,backup],outcomes,simple,{QB:0,RB:0,WR:0,TE:0,K:0,DST:0});
assert.equal(value,130,'Starter chosen before outcomes: 10 + fixed backup insurance, not hindsight 1000');
const pool=Array.from({length:45},(_,i)=>({...starter,id:`p${i}`,name:`P${i}`,projectedPoints:300-i*5,pointsByScoring:undefined,value:300-i*5,adp:i+1,risk:{volatility:.05}}));
const config={...simple,userTeam:'A',simulations:4};
const a=analyzeDraft(pool,[],config,['A','B'],{draftMode:'traditional'});
const b=analyzeDraft(pool.map(p=>({...p,risk:{volatility:.6}})),[],config,['A','B'],{draftMode:'traditional'});
for(const p of a.recommendations)assert.deepEqual(p.plan,b.recommendations.find(q=>q.id===p.id).plan,'Latent dispersion cannot alter a candidate continuation plan');
console.log('Bonus scoring, league-rule preservation, baseline guard and no-hindsight tests passed.');
