import assert from 'node:assert/strict';
import {loadModule} from './load-module.mjs';
const preset=await loadModule('../lib/keeper-preset.ts');
const engine=await loadModule('../lib/optimizer.ts');
const {KEEPER_TEAMS:teams,KEEPER_ROWS:rows,KEEPER_TEAM:mine,presetKeepers,presetPlayers,keeperOverallPick,applyKeeperPreset,prepareProfileState,findKeeperPlayer,mergeKeeperPicks,validateKeeperSnapshot}=preset;
const settings=engine.normalizeSettings({userTeam:'Mock team',draftSlot:1,scoring:'ppr',mode:'balanced',starters:{QB:1,RB:2,WR:3,TE:1,FLEX:0,K:1,DST:1},bench:7,simulations:4});
const input={players:[],drafted:[],settings,teams:['Mock team','Other team'],draftMode:'traditional',leagueRosters:[{team:'Mock team',players:['Old roster']}],rostersAreCurrentDraft:true};
const original=structuredClone(input),state=applyKeeperPreset(input),fixed=state.drafted;
assert.deepEqual(input,original,'Preset must not mutate the original draft');
assert.deepEqual(applyKeeperPreset(state),state,'Reload is idempotent');
assert.equal(fixed.length,32);assert.equal(new Set(fixed.map(k=>k.playerId)).size,32);assert.equal(new Set(fixed.map(k=>k.pick)).size,32);
assert.equal(teams.length,12);assert.equal(teams[7],mine);
assert.equal(engine.rosterSize(state.settings),15);assert.equal(state.settings.irSlots,1);
assert.deepEqual(state.settings.starters,{QB:1,RB:2,WR:2,TE:1,K:0,DST:1,FLEX:2});
assert.deepEqual(state.settings.positionLimits,{QB:4,RB:8,WR:8,TE:3,DST:3,K:0});
assert.deepEqual(state.leagueRosters,[]);assert.equal(state.rostersAreCurrentDraft,false);
assert.equal(teams.filter(t=>fixed.filter(k=>k.owner===t).length===2).length,4);
assert.ok(teams.every(t=>[2,3].includes(fixed.filter(k=>k.owner===t).length)));
for(const row of rows){const keeper=fixed.find(k=>k.playerName===row.name);assert.equal(keeper.pick,keeperOverallPick(row));assert.equal(engine.ownerAt(keeper.pick,teams),row.owner);assert.equal(keeper.costRound,row.round);assert.equal(keeper.pickInRound,row.pickInRound);assert.equal(keeper.originalRound,undefined);}
assert.deepEqual(fixed.filter(k=>k.owner===mine).map(k=>[k.playerName,k.costRound,k.pick]).sort(),[['Nico Collins',6,65],['Rashee Rice',12,137]]);
const reserved=engine.keeperSlots(fixed,teams);assert.equal(reserved.size,32);assert.deepEqual(reserved,new Set(fixed.map(k=>k.pick)));
assert.ok(state.players.every(p=>p.hasProjection===false&&p.projectedPoints===0),'Fallback keeper identities must not invent projections');
const aliased=[{id:'cook',name:'James Cook'},{id:'pitts',name:'Kyle Pitts'},{id:'etienne',name:'Travis Etienne'},{id:'robinson',name:"Wan'Dale Robinson"},{id:'achane',name:"De'Von Achane"}];
for(const [name,id] of [['James Cook III','cook'],['Kyle Pitts Sr.','pitts'],['Travis Etienne Jr.','etienne'],['Wan’Dale Robinson','robinson'],['De’Von Achane','achane']])assert.equal(findKeeperPlayer(aliased,name).id,id);
assert.equal(findKeeperPlayer([{id:'a',name:'James Cook'},{id:'b',name:'James Cook Jr.'}],'James Cook III'),undefined,'Ambiguous identities must not silently bind');
assert.equal(presetPlayers(aliased).length,32);assert.equal(presetKeepers(aliased).find(k=>k.playerName==='James Cook III').playerId,'cook');
const pick=(n,id=`player-${n}`)=>({playerId:id,playerName:id,owner:engine.ownerAt(n,teams),pick:n,kind:'draft'});
let picks=[];
const userPicks=[];
for(let n=1;n<=180;n++){
 if(reserved.has(n))continue;
 picks=mergeKeeperPicks(picks,[pick(n)]);
 if(engine.ownerAt(n,teams)===mine)userPicks.push(n);
}
assert.equal(picks.length,148);assert.equal(userPicks.length,13);assert.deepEqual(userPicks.slice(0,2),[8,17]);assert.ok(!userPicks.includes(65)&&!userPicks.includes(137));
for(const team of teams)assert.equal(picks.filter(p=>p.owner===team).length+fixed.filter(k=>k.owner===team).length,15);
assert.deepEqual(mergeKeeperPicks(picks,picks),picks,'Repeated snapshots must not duplicate picks');
assert.deepEqual(mergeKeeperPicks(picks,fixed.map(k=>({...k,kind:'draft'}))),picks,'Feeds may include keeper picks at their reserved slots');
assert.throws(()=>mergeKeeperPicks([],[pick(3)]),/reserved/);
assert.throws(()=>mergeKeeperPicks([],[pick(181)]),/invalid/);
assert.throws(()=>mergeKeeperPicks([],[{...pick(1),owner:mine}]),/belongs/);
assert.throws(()=>mergeKeeperPicks([pick(1)],[pick(1,'different')]),/conflicts/);
assert.throws(()=>mergeKeeperPicks([pick(1)],[pick(2,'player-1')]),/already drafted/);
assert.throws(()=>mergeKeeperPicks([],[{...fixed[0],pick:1,kind:'draft'}]),/Keeper assignment conflicts/);
assert.throws(()=>mergeKeeperPicks([],[pick(1,'kicker')],[{id:'kicker',pos:'K'}]),/no kicker/);
validateKeeperSnapshot({season:2026,leagueName:'Discord League',teams:[...teams].reverse()});
assert.throws(()=>validateKeeperSnapshot({teams:teams.slice(1)}),/do not match/);
assert.throws(()=>validateKeeperSnapshot({teams,season:2025}),/2026/);
assert.throws(()=>validateKeeperSnapshot({teams,leagueName:'Mock draft'}),/Traditional/);
const withDraft=applyKeeperPreset({...state,drafted:[...fixed,pick(1),{...fixed[0],kind:'draft',pick:2}]});
assert.deepEqual(withDraft.drafted.filter(d=>d.kind==='draft'),[pick(1)],'Preserve live picks, removing only known keeper duplicates');
assert.deepEqual(prepareProfileState(input,'mock-league'),input,'Traditional profiles retain their own settings, players and picks');
assert.deepEqual(prepareProfileState(state,'discord-league'),state);
const pool=[...state.players,...Array.from({length:230},(_,i)=>({id:`p${i}`,name:`P${i}`,pos:['QB','RB','WR','TE','DST','K'][i%6],team:'BUF',projectedPoints:400-i,adp:i+1,age:25,dynastyRank:i+1,tier:1,bye:5,season:2026,hasProjection:true,active:true}))];
const result=engine.analyzeDraft(pool,fixed,state.settings,teams,{draftMode:'keeper',season:2026});
assert.equal(result.currentPick,1);assert.equal(result.targetPick,8);assert.equal(result.nextPick,17);assert.ok(result.recommendations.length>0);
assert.ok(result.recommendations.every(p=>p.pos!=='K'&&!fixed.some(k=>k.playerId===p.id)));
const advanced=engine.analyzeDraft(pool,[...fixed,pick(1),pick(2)],state.settings,teams,{draftMode:'keeper',season:2026});assert.equal(advanced.currentPick,4);
console.log('PASS: all 32 screenshot assignments, 180-slot snake replay, keeper aliases, immutable profile isolation, sync protection, roster limits and engine integration.');
