import assert from 'node:assert/strict';
import {loadModule} from './load-module.mjs';
const {requestSiteJson,SiteRequestError}=await loadModule('../lib/client-json.ts');
let options;
const request=(body,status=200,type='application/json')=>requestSiteJson('/api/fantasypros',async(_url,init)=>{options=init;return new Response(body,{status,headers:{'Content-Type':type}});});
assert.deepEqual(await request('{"players":[{"id":"live"}]}'),{players:[{id:'live'}]});
assert.equal(options.credentials,'include');assert.equal(options.headers.Accept,'application/json');assert.equal(options.cache,'no-store');
for(const status of [401,403])await assert.rejects(request('<!DOCTYPE html><html>Sign in</html>',status,'text/html'),e=>e instanceof SiteRequestError&&e.needsSignIn&&!e.message.includes('Unexpected token'));
for(const status of [200,404,502,503])await assert.rejects(request('<!DOCTYPE html><html>Gateway</html>',status,'text/html'),e=>!e.needsSignIn&&e.message.includes(`HTTP ${status}`));
await assert.rejects(request('{broken'),/incomplete data/);
await assert.rejects(request('null'),/invalid dataset/);
await assert.rejects(request('{"error":"Upstream temporarily unavailable"}',502),/Upstream temporarily unavailable/);
await assert.rejects(requestSiteJson('/api/fantasypros',async()=>{throw Error('network');}),/could not reach/);
await assert.rejects(requestSiteJson('/api/fantasypros',async()=>({status:200,redirected:true,url:'https://example.test/signin-with-chatgpt'})),e=>e.needsSignIn);
const {startAnalysis}=await loadModule('../lib/analysis-runner.ts');
const {applyKeeperPreset,KEEPER_TEAMS}=await loadModule('../lib/keeper-preset.ts');
const {normalizeSettings}=await loadModule('../lib/optimizer.ts');
const state=applyKeeperPreset({players:Array.from({length:200},(_,i)=>({id:`p${i}`,name:`P${i}`,pos:['QB','RB','WR','TE','DST','K'][i%6],team:'BUF',projectedPoints:400-i,adp:i+1,age:25,dynastyRank:i+1,tier:1,bye:5,season:2026,hasProjection:true,active:true})),drafted:[],settings:normalizeSettings({userTeam:'',draftSlot:1,scoring:'standard',mode:'balanced',starters:{QB:1,RB:2,WR:2,TE:1,FLEX:2,K:0,DST:1},simulations:4})});
const input={...state,teams:KEEPER_TEAMS,context:{draftMode:'keeper',season:2026}};
const before=structuredClone(input);
const fake=()=>({postMessage(){},terminate(){},onmessage:null,onerror:null,onmessageerror:null});
const run=factory=>new Promise((resolve,reject)=>startAnalysis(input,factory,resolve,reject));
const failure=await run(()=>{throw Error('Worker blocked');});assert.equal(failure.targetPick,8);assert.ok(failure.recommendations.length);
const scriptError=fake();scriptError.postMessage=()=>queueMicrotask(()=>scriptError.onerror({preventDefault(){}}));assert.deepEqual(await run(()=>scriptError),failure);
const messageError=fake();messageError.postMessage=()=>queueMicrotask(()=>messageError.onmessageerror({}));assert.deepEqual(await run(()=>messageError),failure);
const invalidMessage=fake();invalidMessage.postMessage=()=>queueMicrotask(()=>invalidMessage.onmessage({data:{error:'failed'}}));assert.deepEqual(await run(()=>invalidMessage),failure);
const working=fake();working.postMessage=()=>queueMicrotask(()=>working.onmessage({data:{analysis:failure}}));assert.deepEqual(await run(()=>working),failure);
let earlyCount=0,finalCount=0;const progressive=fake();
await new Promise((resolve,reject)=>{startAnalysis(input,()=>progressive,()=>{finalCount++;resolve();},reject,()=>earlyCount++);progressive.onmessage({data:{pickReady:{player:{id:'ready'}}}});assert.equal(earlyCount,1);assert.equal(finalCount,0);progressive.onmessage({data:{analysis:failure}});});
assert.equal(finalCount,1,'A ready-pick message must not terminate analysis or start fallback');
let callbacks=0;const stale=fake();const cancel=startAnalysis(input,()=>stale,()=>callbacks++,()=>callbacks++);cancel();stale.onmessage({data:{analysis:failure}});stale.onerror({});
let staleReady=0;const staleProgress=fake();const cancelProgress=startAnalysis(input,()=>staleProgress,()=>callbacks++,()=>callbacks++,()=>staleReady++);cancelProgress();staleProgress.onmessage({data:{pickReady:{player:{id:'old'}}}});assert.equal(staleReady,0);
const cancelFallback=startAnalysis(input,()=>{throw Error('blocked');},()=>callbacks++,()=>callbacks++);cancelFallback();
await new Promise(resolve=>setTimeout(resolve,20));assert.equal(callbacks,0,'Cancelled/profile-switched work cannot replace the current analysis');assert.deepEqual(input,before,'Failures cannot mutate saved picks or players');
console.log('PASS: JSON success, sign-in HTML, server HTML, malformed JSON, network failure, worker startup/script/message failures, bundled fallback and cancellation.');
