import assert from 'node:assert/strict';
import {loadModule} from './load-module.mjs';
const {teamRosters}=await loadModule('../lib/team-rosters.ts');
const teams=Array.from({length:12},(_,i)=>`Team ${i+1}`);
const picks=[{playerId:'k',playerName:'Keeper',owner:'Team 8',pick:0,kind:'keeper',costRound:6,pickInRound:5},{playerId:'p',owner:'Team 8',pick:8,kind:'draft'},{playerId:'missing',playerName:'Unmatched Player',owner:'Old team name',pick:9,kind:'draft'}];
const players=[{id:'p',name:'Drafted Player',pos:'WR',team:'HOU'}];
const before=JSON.stringify(picks);
const result=teamRosters(teams,picks,players,'Team 8');
assert.equal(result.length,13);
assert.equal(result[7].isUser,true);
assert.deepEqual(result[7].entries.map(p=>p.overall),[8,65]);
assert.equal(result[7].entries[0].name,'Drafted Player');
assert.equal(result[7].entries[1].inRound,5);
assert.equal(result[12].entries[0].name,'Unmatched Player');
assert.equal(result[0].entries.length,0);
assert.equal(teamRosters(teams,picks.slice(0,1),players,'Team 8')[7].entries.length,1);
assert.equal(JSON.stringify(picks),before);
assert.equal(teamRosters(teams,[{...picks[0],pickInRound:undefined}],players,'Team 8')[7].entries[0].overall,65);
console.log('Roster grouping, keeper slots, unknown players/owners, empty teams, updates and source immutability passed.');
