import type {ReactNode} from 'react';
import type {DraftAnalysis,DraftRecommendation} from '@/lib/optimizer';
import type {LeagueSettings,Player} from '@/lib/draft';
import {decisionNotes,slotSummary,workloadSummary} from '@/lib/decision-copy';

export function PlayerCautions({player}:{player:DraftRecommendation}){
 const notes=decisionNotes(player.issues);
 return <div className="space-y-3 py-2 text-sm">
  <p><span className="font-medium">Projected workload:</span> {workloadSummary(player)}<br/><span className="text-muted-foreground">Already included in projected points; not an extra scoring bonus.</span></p>
  <p><span className="font-medium">Draft market:</span> {player.adp>0&&player.adp<900?`${player.adpSource==='rank-proxy'?'ADP rank':'Average pick'} ${player.adp.toFixed(1)}`:'ADP unavailable'} · {player.consensusRank&&player.consensusRank<900?`Expert rank ${player.consensusRank}`:'Expert rank unavailable'}</p>
  {notes.filter(n=>n.attention).map(n=><p key={n.text} className="rounded-md border border-amber-200 bg-amber-50 p-3 text-amber-950">{n.text}</p>)}
  {notes.some(n=>!n.attention)&&<details><summary className="cursor-pointer font-medium">Source notes</summary><ul className="mt-2 list-disc space-y-2 pl-5 text-muted-foreground">{notes.filter(n=>!n.attention).map(n=><li key={n.text}>{n.text}</li>)}</ul></details>}
 </div>;
}

export function DecisionSummary({analysis,best,settings,players,lastSync,analyzing,children}:{analysis:DraftAnalysis|null;best?:DraftRecommendation;settings:LeagueSettings;players:Player[];lastSync:string;analyzing:boolean;children?:ReactNode}){
 const alerts=decisionNotes([...(analysis?.warnings??[]),...(best?.issues??[])]).filter(n=>n.attention);
 const exploratory=settings.recommendationPolicy==='lookahead';
 return <section className="rounded-2xl border bg-card p-5 sm:p-6" aria-live="polite">
  <div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-lg font-semibold">Why this pick</h2><p className="mt-1 text-sm text-muted-foreground">{exploratory?'Experimental draft planning':'Best projected fit for your roster'} · not a guaranteed outcome</p></div><span className="rounded-full bg-secondary px-3 py-1 text-sm">{analyzing?'Updating…':`${analysis?.eligible??0} usable projections`}</span></div>
  {best&&<div className="mt-5 grid gap-4 sm:grid-cols-3"><div><p className="text-sm text-muted-foreground">Season projection</p><p className="mt-1 text-2xl font-semibold">{best.projectedValue.toFixed(1)} <span className="text-sm font-normal">points</span></p><p className="mt-1 text-sm">Adjusted to your league’s scoring</p></div><div><p className="text-sm text-muted-foreground">Estimated roster improvement</p><p className="mt-1 text-2xl font-semibold">{best.marginalPoints>=0?'+':''}{best.marginalPoints.toFixed(1)}</p><p className="mt-1 text-sm">Includes starters, bye cover and bench value—not extra player points</p></div><div><p className="text-sm text-muted-foreground">Open starting spots</p><p className="mt-1 text-lg font-semibold">{slotSummary(analysis?.openSlots??[])}</p><p className="mt-1 text-sm">Updates after every recorded pick</p></div></div>}
  {alerts.length>0&&<div className="mt-5 space-y-2"><h3 className="text-sm font-semibold">Before you pick</h3>{alerts.map(n=><p key={n.text} className="rounded-lg border border-amber-200 bg-amber-50 p-3 text-sm text-amber-950">{n.text}</p>)}</div>}
  <p className="mt-5 text-sm text-muted-foreground">{lastSync?`Last download: ${new Date(lastSync).toLocaleString()}.`:'Live data has not been downloaded for this profile.'} {players.length} players in the pool; {analysis?.excluded??0} excluded from recommendations. A missing expert update time is not the same as a failed download.</p>
  {best?.newsHeadline&&<div className="mt-4 rounded-lg bg-secondary p-4"><h3 className="text-sm font-semibold">Latest player news</h3><p className="mt-2 font-medium">{best.newsHeadline}</p><p className="mt-1 text-sm">{best.newsBody}</p><p className="mt-2 text-sm text-muted-foreground">{best.newsUpdatedAt?new Date(best.newsUpdatedAt).toLocaleString():'Publication time not supplied'} · Review whether projections have caught up.</p></div>}
  {best&&<details className="mt-5 border-t pt-4"><summary className="cursor-pointer text-sm font-medium">Player data & availability review</summary><PlayerCautions player={best}/>{children}</details>}
  <details className="mt-4 border-t pt-4"><summary className="cursor-pointer text-sm font-medium">What the picker uses—and what it doesn’t</summary><div className="mt-3 space-y-3 text-sm text-muted-foreground"><p><b className="text-foreground">Directly affects the default pick:</b> league-adjusted projections, your roster and open slots, position limits, estimated replacement players, bye-week cover and diminishing value of extra bench players. Recorded picks and keepers determine who is available.</p><p><b className="text-foreground">Supporting context:</b> ADP and expert ranks guide market estimates and tie-breaks. Opponent needs, draft runs, expert disagreement and news inform exploratory scenarios. News is not automatically turned into guessed point penalties. Dynasty rankings and future keeper values do not override the default pick.</p><p><b className="text-foreground">Not yet modeled as an independent edge:</b> route and target-share trends, goal-line opportunities, depth-chart changes, ESPN-specific draft-room preferences and calibrated teammate injury effects. More inputs are useful only if testing shows that they add information beyond the existing projections.</p><p><b className="text-foreground">Evidence:</b> the complex lookahead policy did not beat the simpler roster-value policy in the final historical test. Neither policy is proven to be the absolute best for your keeper league. Availability estimates are model scenarios, not measured odds.</p><p>Historical research used archived PPR rankings, estimated rank-to-points forecasts, simulated opponents and frozen lineups without waiver moves. One untouched season is not proof of general superiority. Defense points-allowed bonuses are historical estimates, not exact provider projections.</p><p><a className="underline" href="https://nflreadr.nflverse.com/articles/nflverse_data_schedule.html" target="_blank" rel="noreferrer">nflverse data availability</a> · <a className="underline" href="https://www.fantasypros.com/about/faq/football-draft-accuracy-methodology/" target="_blank" rel="noreferrer">FantasyPros accuracy methodology</a></p></div></details>
  <details className="mt-4 border-t pt-4"><summary className="cursor-pointer text-sm font-medium">Technical diagnostics & exploratory plan</summary><div className="mt-3 space-y-3 text-sm text-muted-foreground"><p>{analysis?.comparison}</p><p>{analysis?.candidateCount??0} shortlisted choices · {analysis?.simulations??0} scenarios per choice. {best?.plan.join(' → ')}</p>{best&&<p>Exploratory model value: {best.score.toFixed(1)}. {exploratory?'Experimental comparisons affect the ordering.':'This number does not determine the default ordering.'}</p>}{[...new Set([...(analysis?.warnings??[]),...(best?.issues??[])])].map(w=><p key={w}>{w}</p>)}</div></details>
 </section>;
}
