'use client';
import { useState } from 'react';
import { Input } from '@/components/ui/input';
import { Button } from '@/components/ui/button';
import { Textarea } from '@/components/ui/textarea';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import type { LeagueSettings, Player, Position } from '@/lib/draft';
import { DEFAULT_KEEPER_RULES, STANDARD_SCORING, STAT_LABELS } from '@/lib/optimizer';
import { applyDiscordRules } from '@/lib/discord-rules';

export function EngineSettings({ settings: s, onChange, keeper }: { settings: LeagueSettings; onChange: (s: LeagueSettings) => void; keeper: boolean }) {
  const [advanced, setAdvanced] = useState(''); const [positionRules,setPositionRules]=useState(''); const [error,setError]=useState('');
  const update = (value: Partial<LeagueSettings>) => onChange({...s,...value,rulesConfirmed:false});
  const rules={...DEFAULT_KEEPER_RULES,...s.keeperRules};
  return <details className="rounded-lg border p-3" open><summary className="cursor-pointer text-sm font-semibold">Optimizer rules & assumptions</summary>
    <p className="my-3 text-sm text-muted-foreground">Confirm these against your ESPN league. Imported settings are not automatically assumed complete.</p>
    <label className="text-sm font-medium">Recommendation policy</label><Select value={s.recommendationPolicy??'roster-value'} onValueChange={v=>update({recommendationPolicy:v as 'roster-value'|'lookahead'})}><SelectTrigger className="my-2 w-full"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="roster-value">Roster value — evidence-gated default</SelectItem><SelectItem value="lookahead">Experimental lookahead + keeper option model</SelectItem></SelectContent></Select>
    <p className="mb-3 text-xs text-muted-foreground">The default uses scoring, roster needs, replacement levels, bye coverage and useful depth. It shows but does not optimize speculative future keeper value. Experimental lookahead uses full-draft simulations and keeper options, without a proven historical advantage. Neither is a guaranteed best pick.</p>
    <Button variant="secondary" className="mb-3" onClick={()=>onChange(applyDiscordRules(s))}>Use verified Discord League rules</Button>
    {s.scoringSource&&<p className="mb-3 text-sm text-muted-foreground">Scoring source: {s.scoringSource}. Draft order, picks and keeper contracts are preserved. Confirm keeper edge-case rules separately.</p>}
    <div className="grid grid-cols-3 gap-2">{Object.entries(s.starters).map(([pos,n])=><label key={pos} className="text-sm">{pos}<Input aria-label={`${pos} starters`} type="number" min={0} max={10} value={n} onChange={e=>update({starters:{...s.starters,[pos]:Math.max(0,Math.min(10,Number(e.target.value)))}})}/></label>)}
      <label className="text-sm">Superflex<Input aria-label="Superflex starters" type="number" min={0} max={4} value={s.superflex??0} onChange={e=>update({superflex:Math.max(0,Math.min(4,Number(e.target.value)))})}/></label>
      <label className="text-sm">Bench<Input aria-label="Bench slots" type="number" min={0} max={20} value={s.bench??6} onChange={e=>update({bench:Math.max(0,Math.min(20,Number(e.target.value)))})}/></label>
    </div>
    <details className="mt-3"><summary className="cursor-pointer text-sm font-medium">Position limits & custom scoring</summary>
      <p className="my-2 text-sm text-muted-foreground">Blank position limit = no extra limit. Defaults shown are the provider baseline, including −1 per interception; confirm your ESPN rules. Overrides are points per statistic, not extra bonuses. Missing statistics produce warnings.</p>
      <div className="grid grid-cols-3 gap-2">{(['QB','RB','WR','TE','K','DST'] as Position[]).map(pos=><label key={pos} className="text-sm">Max {pos}<Input aria-label={`Maximum ${pos}`} type="number" min={0} max={30} placeholder="No limit" value={s.positionLimits?.[pos]??''} onChange={e=>update({positionLimits:{...s.positionLimits,[pos]:e.target.value===''?undefined:Math.max(0,Number(e.target.value))}})}/></label>)}</div>
      <div className="mt-3 grid grid-cols-2 gap-2">{Object.entries(STAT_LABELS).map(([stat,label])=><label key={stat} className="text-sm">{label}<Input aria-label={`${label} scoring`} type="number" step="0.01" value={s.customScoring?.[stat]??(stat==='rec'?(s.scoring==='ppr'?1:s.scoring==='half-ppr'?.5:0):STANDARD_SCORING[stat])} onChange={e=>update({customScoring:{...s.customScoring,[stat]:Number(e.target.value)}})}/></label>)}</div>
      <p className="my-2 text-sm text-muted-foreground">Advanced JSON: projection-stat coefficients, including K/DST (fg, xpt, def_sack, def_int, def_fr, def_td, def_safety). Missing milestone projections still require evidence. For field-goal distance and defensive points allowed, configure the bands below: the engine estimates event counts from historical nflverse data and labels them separately from FantasyPros projections.</p>
      <Textarea aria-label="Advanced scoring JSON" value={advanced} onChange={e=>setAdvanced(e.target.value)} placeholder={'{"pass_yds_300": 3}'}/>
      <Button className="mt-2" variant="secondary" onClick={()=>{try{const v=JSON.parse(advanced);if(!v||Array.isArray(v)||Object.values(v).some(x=>typeof x!=='number'||!Number.isFinite(x)))throw Error('Use an object with finite numeric coefficients.');update({customScoring:{...s.customScoring,...v}});setError('');}catch(e){setError(e instanceof Error?e.message:'Invalid JSON');}}}>Apply advanced scoring</Button>
      <p className="my-2 text-sm">Position-specific scoring (for example TE premium)</p><Textarea aria-label="Position-specific scoring JSON" value={positionRules} onChange={e=>setPositionRules(e.target.value)} placeholder={'{"TE":{"rec":1.5},"DST":{"def_sack":2}}'}/>
      <Button className="mt-2" variant="secondary" onClick={()=>{try{const v=JSON.parse(positionRules);if(!v||Array.isArray(v)||Object.entries(v).some(([pos,rules])=>!['QB','RB','WR','TE','K','DST'].includes(pos)||!rules||typeof rules!=='object'||Array.isArray(rules)||Object.values(rules).some(x=>typeof x!=='number'||!Number.isFinite(x))))throw Error('Use position names mapped to numeric scoring coefficients.');update({positionScoring:v});setError('');}catch(e){setError(e instanceof Error?e.message:'Invalid JSON');}}}>Apply position scoring</Button>
      <Button className="mt-2" variant="ghost" onClick={()=>update({customScoring:undefined,positionScoring:undefined})}>Reset scoring overrides</Button>{error&&<p role="alert" className="text-sm text-red-700">{error}</p>}
      {(s.customScoring||s.positionScoring)&&<p className="mt-2 break-words text-sm text-muted-foreground">Saved overrides: {JSON.stringify({all:s.customScoring,byPosition:s.positionScoring})}</p>}
    </details>
    <details className="mt-3" open={!!s.bonusRules}><summary className="cursor-pointer text-sm font-medium">Historical bonus estimates</summary>
      <p className="my-2 text-sm text-muted-foreground">Band values are total points, not extra points. Estimates apply only when the provider baseline is verified and the model matches the season. They are not exact event forecasts.</p>
      {([['fieldGoals','Made FG: 0–39 / 40–49 / 50+ yards',[3,4,5]],['pointsAllowed','DST allowed: 0 / 1–6 / 7–13 / 14–20 / 21–27 / 28–34 / 35+',[10,7,4,1,0,-1,-4]]] as const).map(([key,label,defaults])=><div key={key} className="my-2"><label className="text-sm"><input type="checkbox" checked={!!s.bonusRules?.[key]} onChange={e=>update({bonusRules:{...s.bonusRules,[key]:e.target.checked?[...defaults]:undefined}})}/> {label}</label>{s.bonusRules?.[key]&&<div className="mt-1 flex gap-1">{s.bonusRules[key]!.map((n,i)=><Input key={i} aria-label={`${key} band ${i+1}`} type="number" step="0.1" value={n} onChange={e=>update({bonusRules:{...s.bonusRules,[key]:s.bonusRules![key]!.map((v,j)=>j===i?Number(e.target.value):v)}})}/>)}</div>}</div>)}
      <p className="text-xs text-muted-foreground">Kicker distance mix uses the league prior selected in development. DST uses heavily shrunk team history. Held-out 2023–2025 seasonal bonus MAE: ~3.5 K points conditional on made FGs, ~11.7 DST points under Discord scoring. Custom band weights can have different error. <a href="https://github.com/nflverse/nflverse-data" target="_blank" rel="noreferrer" className="underline">nflverse data, CC BY 4.0</a>; trained through 2025.</p>
    </details>
    {keeper&&<div className="mt-4 space-y-2"><p className="text-sm font-semibold">Keeper contract rules</p><div className="grid grid-cols-2 gap-2">{([['limit','Keeper limit',0,10],['escalation','Rounds earlier/year',1,5],['horizon','Future years',1,5],['discount','Annual discount',0,1]] as const).map(([key,label,min,max])=><label key={key} className="text-sm">{label}<Input aria-label={label} type="number" min={min} max={max} step={key==='discount'?.05:1} value={rules[key]} onChange={e=>update({keeperRules:{...rules,[key]:Math.max(min,Math.min(max,Number(e.target.value)))}})}/></label>)}</div>
      <p className="text-sm">When cost would precede round one</p><Select value={rules.firstRound} onValueChange={v=>update({keeperRules:{...rules,firstRound:v as typeof rules.firstRound}})}><SelectTrigger className="w-full"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="ineligible">Cannot keep (assumption)</SelectItem><SelectItem value="round-one">Keep at round one</SelectItem></SelectContent></Select>
      <p className="text-sm">Duplicate round costs</p><Select value={rules.collision} onValueChange={v=>update({keeperRules:{...rules,collision:v as typeof rules.collision}})}><SelectTrigger className="w-full"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="earlier">Move to earlier free round</SelectItem><SelectItem value="reject">Cannot keep both</SelectItem></SelectContent></Select>
    </div>}
    <label className="mt-3 block text-sm">Risk aversion (0 = expected value; 1 = stronger downside preference)<Input aria-label="Risk aversion" type="number" min={0} max={1} step={.05} value={s.riskTolerance??.15} onChange={e=>update({riskTolerance:Math.max(0,Math.min(1,Number(e.target.value)))})}/></label>
    <label className="mt-3 block text-sm">Simulated draft worlds<Input aria-label="Simulated draft worlds" type="number" min={4} max={32} value={s.simulations??12} onChange={e=>update({simulations:Math.max(4,Math.min(32,Number(e.target.value)))})}/></label>
    <Button className="mt-3 w-full" variant={s.rulesConfirmed?'secondary':'default'} onClick={()=>onChange({...s,rulesConfirmed:true})}>{s.rulesConfirmed?'League rules confirmed':'Confirm these league rules'}</Button>
  </details>;
}

export function PlayerRiskEditor({player,onSave}:{player:Player;onSave:(risk:Player['risk'])=>void}) {
  const [games,setGames]=useState(player.risk?.missedGames??0); const [included,setIncluded]=useState(player.risk?.projectionIncludesAbsence??true);const [note,setNote]=useState(player.risk?.note??'');
  return <details className="mt-3 rounded-lg border p-3"><summary className="cursor-pointer text-sm font-medium">Review availability: {player.name}</summary><p className="my-2 text-sm text-muted-foreground">Use a sourced estimate, not the injury designation alone. If projections already include the absence, do not subtract it again.</p><label className="text-sm">Expected missed games<Input aria-label="Expected missed games" type="number" min={0} max={17} value={games} onChange={e=>setGames(Math.max(0,Math.min(17,Number(e.target.value))))}/></label><Select value={included?'included':'subtract'} onValueChange={v=>setIncluded(v==='included')}><SelectTrigger className="my-2 w-full"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="included">Already reflected in projections</SelectItem><SelectItem value="subtract">Deduct from projection</SelectItem></SelectContent></Select><Input aria-label="Availability evidence" placeholder="Source / reason for this estimate" value={note} onChange={e=>setNote(e.target.value)}/><Button className="mt-2" variant="secondary" disabled={!note.trim()} onClick={()=>onSave({missedGames:games,projectionIncludesAbsence:included,note})}>Save availability review</Button></details>;
}
